# Site settings
title: News - Annotator - Annotating the Web
email: info@annotatorjs.org
description: "Write an awesome description for your new site here. You can edit this line in _config.yml. It will appear in your document head meta (for Google search results) and in your feed.xml site description."
baseurl: "../news"
url: "http://annotatorjs.org"
destination: "../news/"

# Build settings
markdown: kramdown
permalink: none
exclude: [Rakefile, JEKYLL_README]
